### ISSUE TITLE
Need resize options.

### ISSUE THREAD

**Issue by dawnbomb** [CroatianHusky/tg-stickers#3]
Can we please get an option to copy a resized version of a sticker. One that will always be the same size as telegram? As it is now, it copys the original images, pasting them to discord makes them extremely large.

**Comment by sleddev** [comment]
Oh hey, I didn't think anyone was using this besides me lol

But anyway, I can look into adding resizing. 
I'm relatively busy nowadays, so I don't know how long it will take.

I think I'll do it by adding an option in the settings, where you can select a resolution that you want.

Any suggestions on how you would like to see this implemented?

**Comment by dawnbomb** [comment]
Oh heck, a reply!

My toronto local group uses this, but its not like theres a forum, "tg stickers" is not really a name you tell people, like you dont say "use tg stickers" you say "theres this program to use telegram stickers everywhere, here you go!" and nobody ever says its name. Also, the github changes requiring 2FA (requiring a phone) scares some people off of signup (if they lose their phone, their screwed). Finally, the program works, so... theres not much to open issues for! :0

Okay, in options you have always run on top as the only option.
- Add dropdown box for copied resolution. 
All stickers in all programs are always squares.
In discord, stickers are an internal resolution of 320, but rendered at 160. (Exactly half)
In Telegram, Stickers are an internal resolution of 512, and this would imply they render at 256 (50%)
They do not. They *appear* to render at 230.4 (45%). I suspect, as i'm in game design, this is to emphasize the crunchiness of the pixels, and offer a more satisfying image.  I suspect discord res would want the same. We can ssume it would go to 30% at 153.6px
So i (probably) recommend these dropdown options...
100% Native (512px)
50% Half (256px)
45% Telegram Size (230px)
30% Discord Size (153px)
31.25% True Discord size (160px)


- Add option for start when PC starts?
- Make the search bar an option. Its mostly just in the way.
- Make vertical resizing the window itself an option? On telegram, we often have a tall sticker window.
- Maybe instead of just "always on top, also add an option for, if discord is the active window, make this ontop. Otherwise hide. 
(Obviously hooking into better discord as a plugin would be VASTLY better, but, i assume you don't wanna bother figuring that shit out lul) 

(But seriously if you could make it a plugin, like a new button next to the discord sticker button for telegram stickers, that would be fire)

Im a C# coder myself, and this is in every language EXCEPT C#. >:0

**Comment by sleddev** [comment]
Oh wow, thats quite the detailed response, thank you.

- Those dropdown options seem rational, sounds good.
- You can achieve this by placing a shortcut for `tgs-tray.exe` into the startup folder (`“C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup”`), thats how I have it on my pc. It could be done automatically and I may do it, but that's not the highest priority I think.
- Sure I can add the search bar toggle, should be trivial.
- Vertical resizing is also doable. I'll have to figure out how to enable vertical resize only, but I think the UI will work with it as-is.
- Now this one seems a bit more complicated. I guess it could be done with some title hackery, searching inside the active window's title or class.  Yeah I dont want to get into discord plugins. I would need to rewrite it for both betterdiscord and vencord. I tried making betterdiscord plugins once, but the tooling and documentation was seriously lacking.

Yeah github lists a bunch of languages, but its really only two. The app is written in Dart with the Flutter framework, and the background service is in C++

Again, I'm relatively busy lately, but I will try to set aside some time for working on this project again, as I don't want it to turn into abandonware. And thank you for the helpful insights!

**Comment by dawnbomb** [comment]
I'll be hopeful for resize output options. 
the program is only useful, if others don't think the image size is stupid unfunny and intrusive. as it is the images are so large, they clog the entire discussion, unlike sticker sized that purely adds expression to conversation.

I'll be watching :0

**Comment by sleddev** [comment]
Good news @dawnbomb 

I managed to have some free time (read: I stayed up all night, its 5am here lol), and so I implemented hiding the search bar, vertical resizing of the window, and added the 5 sticker resizing options.

**Comment by dawnbomb** [comment]
I'll try it out in the morning..or rather around noon when i wake up. 
:D

**Comment by dawnbomb** [comment]
Okay i used it for a week. Its fantastic, thanks!
I had others asking about it now as well. Were all very pleased. :)

**Comment by sleddev** [comment]
That's great to hear, glad I could help!
